spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/auth/**, /api/v1/user/**, /api/v1/admin/**, /api/v1/expert/**, /api/v1/investigator/**, /api/v1/lawyer/**, /api/v1/judge/**

        - id: report-service
          uri: lb://REPORT-SERVICE
          predicates:
            - Path=/api/v1/report/**, /api/v1/reports/**, /api/v1/templates/**

        - id: image-analysis-service
          uri: lb://IMAGEANALYSIS-SERVICE
          predicates:
            - Path=/api/v1/analysis/**

        - id: image-management-service
          uri: lb://IMAGEMANAGEMENT-SERVICE
          predicates:
            - Path=/api/v1/images/**

server:
  port: 8222
